"""Module 7 – Local Markdown Report Generation.

Generates a formatted Markdown report saved as
``reports/YYYY-MM-DD_intraday_report.md``.
"""

import logging
from datetime import datetime

import pytz

from .config import REPORTS_DIR

logger = logging.getLogger(__name__)


def _format_ticker_section(cand: dict) -> str:
    """Build a Markdown section for one selected ticker."""
    ticker = cand["ticker"]
    lines = [
        f"### {ticker}",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Positive Sentiment Score | {cand.get('compound', 'N/A'):.3f} |" if isinstance(cand.get('compound'), (int, float)) else f"| Positive Sentiment Score | {cand.get('compound', 'N/A')} |",
        f"| Best Headline Score | {cand.get('best_score', 'N/A'):.3f} |" if isinstance(cand.get('best_score'), (int, float)) else f"| Best Headline Score | {cand.get('best_score', 'N/A')} |",
        f"| Primary Positive Headline | {cand.get('best_headline', 'N/A')} |",
        f"| Pre-Market Entry Level | ${cand['premarket_price']:.2f} |" if cand.get('premarket_price') else "| Pre-Market Entry Level | N/A |",
        f"| RSI (14) | {cand.get('rsi', 'N/A')} |",
        f"| Price Velocity (5-day) | {cand.get('price_velocity', 'N/A')}% |",
        f"| Pre-Market Volume Ratio | {cand.get('volume_ratio', 'N/A')} |",
        f"| Geo Risk Hits | {cand.get('geo_risk_hits', 0)} |",
        f"| Sector | {cand.get('ticker_sector', 'N/A')} |",
        f"| Regime Alignment | {', '.join(cand.get('regime_themes', [])) or 'Neutral'} |",
        f"| Regime Score | {cand.get('regime_score', 0):+.0f} |",
    ]

    # Stress-test results
    penalties = cand.get("stress_penalties", {})
    passed = cand.get("stress_passed", False)
    lines.append(f"| Stress-Test Result | {'PASSED' if passed else 'CONDITIONAL PASS'} |")
    lines.append(f"| → Resistance Penalty | {penalties.get('resistance', 0):.0f} |")
    lines.append(f"| → Volume Dry-Up Penalty | {penalties.get('volume_dryup', 0):.0f} |")
    lines.append(f"| → Data Gap Penalty | {penalties.get('data_gap', 0):.0f} |")
    lines.append("")

    return "\n".join(lines)


def generate_report(
    final_picks: list[dict],
    general_news: list[dict],
    all_stage_counts: dict,
) -> str:
    """Generate the dated Markdown report and write it to disk.

    Returns the file path of the generated report.
    """
    london = pytz.timezone("Europe/London")
    now_uk = datetime.now(london)
    date_str = now_uk.strftime("%Y-%m-%d")
    time_str = now_uk.strftime("%H:%M %Z")

    report_path = REPORTS_DIR / f"{date_str}_intraday_report.md"

    lines = [
        f"# Morning Intraday Stock Scanner Report",
        f"## {date_str} — Generated at {time_str}",
        "",
        "---",
        "",
        "## Pipeline Summary",
        "",
        f"| Stage | Tickers |",
        f"|-------|---------|",
        f"| S&P 500 Universe | {all_stage_counts.get('universe', '?')} |",
        f"| Stage 1: Sentiment Filter | {all_stage_counts.get('sentiment', '?')} |",
        f"| Stage 2: Geopolitical Filter | {all_stage_counts.get('geopolitical', '?')} |",
        f"| Stage 2.5: Regime Alignment | {all_stage_counts.get('regime', '?')} |",
        f"| Stage 3: Technical Filter | {all_stage_counts.get('technical', '?')} |",
        f"| Stage 4: Stress-Test Survivors | {all_stage_counts.get('stress', '?')} |",
        "",
        "---",
        "",
        "## Dominant Morning Geopolitical Themes",
        "",
    ]

    # Top macro headlines
    if general_news:
        seen = set()
        count = 0
        for article in general_news:
            headline = article.get("headline", "")
            if not headline or headline in seen:
                continue
            seen.add(headline)
            source = article.get("source", "")
            lines.append(f"- **{source}**: {headline}")
            count += 1
            if count >= 10:
                break
    else:
        lines.append("- _No macro headlines available._")

    lines.extend([
        "",
        "---",
        "",
        f"## Final Selections ({len(final_picks)} Tickers)",
        "",
    ])

    if final_picks:
        for cand in final_picks:
            lines.append(_format_ticker_section(cand))
    else:
        lines.append("_No tickers survived the full pipeline today._")
        lines.append("")

    lines.extend([
        "---",
        "",
        "_This report is auto-generated by the Morning Stock Scanner pipeline._",
        f"_Disclaimer: This is not financial advice. Perform your own due diligence._",
        "",
    ])

    report_content = "\n".join(lines)
    report_path.write_text(report_content, encoding="utf-8")
    logger.info("Report written to %s", report_path)

    return str(report_path)
